name: Facticles
favicon: null
layout_spectrum: 0.50734
typography_spectrum: 0.09343
title: Facticles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e2e19'
    - '#81562c'
    - '#010101'
    - '#986f3a'
    - '#a3805f'
  brandStrength: 0.4375
  lightness: 0.8202174126636237
  saturation: 0.6350492187775671
  rhythmicContrast: 0.25
purpose: []
